print("Welcome to the tip calculator")
bill = float(input("What was the total bill? ₹ "))
tip = int(input("What percent tip would you like to give? 10 , 12 or 15? " ))
total_bill = bill *(1 +(tip/100))
split = int(input("How many people to split the bill? "))
final_bill = round(total_bill/split , 2)
print(f"Each person should pay: ₹{final_bill}") 